name: EXE Oluştur (Windows)

on:
  push:
    branches: [ "ana" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v4

    - name: Node.js kur
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Gerekli paketleri yükle
      run: npm install -g pkg

    - name: EXE oluştur
      run: pkg renault_radio_code_fetcher.js --targets node20-win-x64 --output renault_radio_code_fetcher.exe

    - name: EXE dosyasını yükle
      uses: actions/upload-artifact@v4
      with:
        name: renault-exe-win64
        path: renault_radio_code_fetcher.exe
